name: Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run format
      - run: npm run lint
      - run: npm test